development:
  adapter: postgresql
  encoding: unicode
  database: saasbook
  pool: 5
  username: saasbook
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: saasbook
  pool: 5
  username: saasbook
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: saasbook
  pool: 5
  username: saasbook
  password: