development:
  adapter: postgresql
  encoding: unicode
  database: saasbook
  pool: 5

  username: saasbook
  password:
test:

  timeout: 5000

  adapter: postgresql

  encoding: unicode
  database: idlecampus

  username: saasbook
  password:
production:
  adapter: postgresql
  encoding: unicode

  database: saasbook


  username: saasbook
  password:

